services:
  - type: web
    name: social-media-downloader-api
    env: docker
    region: oregon  # You can change this to your preferred region
    plan: free      # You can change to starter or higher if needed
    branch: main
    buildCommand: echo "Using Dockerfile for build"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /app
    disk:            # Optional: Add persistent disk if needed
      name: temp-storage
      mountPath: /app/temp
      sizeGB: 1